/**: # namespace and node name
  ros__parameters:
    kp_psi: 2.0
    ki_psi: 0.0
    kd_psi: 1.0
    saturation_psi: 200

    kp_u: 20.0
    ki_u: 0.0
    kd_u: 0.0
    saturation_u: 300

    desired_u: 0.5
    thruster_pwm: 1500 # Basic PWM value for thruster (1550, 1575, 1600)
    thruster_pwm_min: 0 # Minimum threshold for thruster PWM
    thruster_pwm_max: 2300 # Maximum threshold for thruster PWM
    thruster_wn: 5.0 # Natural frequency for thruster PWM smoother
    thruster_zeta: 1.0 # Damping ratio for thruster PWM smoother
